// action types
const COUNTER_DEC = `COUNTER_DEC`;
const COUNTER_INC = `COUNTER_INC`;
const INPUT_VALUE = `INPUT_VALUE`;
const COUNTER_SET = `COUNTER_SET`;

export { COUNTER_DEC, COUNTER_INC, INPUT_VALUE, COUNTER_SET };
