const actions = {
    COUNTER_DECREMENT: `COUNTER_DECREMENT`,
    COUNTER_INCREMENT: `COUNTER_INCREMENT`,
    INPUT_VALUE_SET: `INPUT_VALUE_SET`,
    COUNTER_SET: `COUNTER_SET`,
    COUNTER_SET_TEN: `COUNTER_SET_TEN`
}

export default actions;