const actions = {
    GET_TODOS: `GET_TODOS`,
    TODOS_ITEM_DELETE: `TODOS_ITEM_DELETE`,
    TODOS_ITEM_CHANGE: `TODOS_ITEM_CHANGE`,
    NEW_TODO_TITLE: `NEW_TODO_TITLE`,
    ADD_NEW_TODO: `ADD_NEW_TODO`
}

export default actions;