const TODOS_SET = `TODOS_SET`;
const TODOS_ITEM_DELETE = `TODOS_ITEM_DELETE`;
const TODOS_ITEM_CHANGE = `TODOS_ITEM_CHANGE`;

const NEW_TODO_TITLE = `NEW_TODO_TITLE`;
const NEW_TODO_COMPLETED = `NEW_TODO_COMPLETED`;
const NEW_TODO_SET = `NEW_TODO_SET`;

const SET_DEFAULT_TODO = `SET_DEFAULT_TODO`;

export default {
  TODOS_SET,
  TODOS_ITEM_DELETE,
  TODOS_ITEM_CHANGE,
  NEW_TODO_TITLE,
  NEW_TODO_COMPLETED,
  NEW_TODO_SET,
  SET_DEFAULT_TODO,
};
